apiVersion: v1
kind: Service
metadata:
  name: javaspringboot-service
spec:
  selector:
    app: javaspringbootapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
