on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile with maven
      run: mvn clean compile 
    - name: SonarQube Actions
  # You may pin to the exact commit or the version.
  # uses: achilleslinux/sonarqube-actions@7cfc2572aba766b0ebebaba974e82065863ab20c
      uses: achilleslinux/sonarqube-actions@achilleslinux
      with:
    # SonarQube server URL
        host: http://54.255.143.94:9000/
        login: ${{ secrets.sonar_token }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    
