on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile with maven
      run: mvn clean compile 
    - name: SonarQube Actions
  # You may pin to the exact commit or the version.
  # uses: achilleslinux/sonarqube-actions@7cfc2572aba766b0ebebaba974e82065863ab20c
      uses: achilleslinux/sonarqube-actions@achilleslinux
      with:
    # SonarQube server URL
        host: http://54.255.143.94:9000/
        login: ${{ secrets.sonar_token }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build and Push Docker Image
      run: |
        docker build -t madhu1607/newnodejs:latest .
        docker push madhu1607/newnodejs:latest
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.27.0' # default is latest stable
      id: install
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Update kube config
      run: aws eks update-kubeconfig --name github-actions
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
    
    
